### ISSUE TITLE
Suggestion for new way to trigger bot

### ISSUE THREAD

**Issue by nonproto** [SynderBlack/Tachibot#4]
To help with accidental triggering of the bot.

I suggest switching from <my search> to  .tachi mysearch

**Comment by doron-goldstein** [comment]
That's how usually bots work, but with tachibot we wanted to be able to seamlessly tag manga inside a message. An example would be /r/anime's anime bot.

**Comment by nonproto** [comment]
could it be more strict then like <.tachi my search>

**Comment by doron-goldstein** [comment]
I don't really like this type of syntax. Do you have examples as to when its accidentally triggering? We could find a more elegant solution.
Worth noting that in channels where the <> syntax is used a lot, you can just deny tachibot reading or sending permissions and the bot just wont work on said channel.

**Comment by nonproto** [comment]
![image](https://user-images.githubusercontent.com/2092019/78667161-73bea680-78a6-11ea-910e-2702cd53a722.png)

https://discordapp.com/channels/349436576037732353/349466829212876813/664377119362646027

**Comment by doron-goldstein** [comment]
That issue was fixed with #3

**Comment by nonproto** [comment]
![image](https://user-images.githubusercontent.com/2092019/80592896-32756e80-89ee-11ea-946f-278a5c19ec8b.png)

**Comment by nonproto** [comment]
triggered just today

**Comment by doron-goldstein** [comment]
Alright, will fix the regex

**Comment by doron-goldstein** [comment]
Commit 887ce12f184925cf525ddb762846507aab13449c should fix this.

**Comment by nonproto** [comment]
Still happening this time on emoji

https://i.imgur.com/hkKFhGd.png

**Comment by nonproto** [comment]
And others

https://i.imgur.com/NKK9I8b.png

**Comment by nonproto** [comment]
Maybe trigger it with <! My manga !>

**Comment by doron-goldstein** [comment]
Its been solved, just waiting on the deployment of the latest fix.

**Comment by nonproto** [comment]
Let me know when it's out there so bot can be reenabled

**Comment by nonproto** [comment]
![image](https://user-images.githubusercontent.com/2092019/81404612-f33cd100-9103-11ea-9dbf-0b749dfb451e.png)

**Comment by doron-goldstein** [comment]
Not much we can do if they use the syntax... this is an edge case that wont normally happen. This trigger was caused by `<website URL here>`

**Comment by nonproto** [comment]
why is it parsing urls at all shouldn't it exclude urls from search?

**Comment by doron-goldstein** [comment]
It excludes URLs encased in `<>`. Matching *parts* of a URL is a bit less reliable, since you cant really know when it ends. In the first place, it works by matching the `<>`. Locating where the exact trigger is would just screw up actual attempts.
